global:
  namespace: staging
  dockeruser: tlavu2004

imageTag: &tag V1.0.5

services:
  api-gateway:
    image:
      tag: *tag
    ingress:
      host: petclinic-staging.com

  config-server:
    image:
      tag: *tag

  discovery-server:
    image:
      tag: *tag

  customers-service:
    image:
      tag: *tag
    
  vets-service:
    image:
      tag: *tag

  visits-service:
    image:
      tag: *tag

