global:
  namespace: default
  dockeruser: tlavu2004

services:
  api-gateway:
    name: api-gateway
    image:
      repository: spring-petclinic-api-gateway
      tag: latest
    port: 8080
    replicaCount: 1
    ingress: 
      host: petclinic.com

  config-server:
    name: config-server
    image:
      repository: spring-petclinic-config-server
      tag: latest
    port: 8888
    replicaCount: 1

  discovery-server:
    name: discovery-server
    image:
      repository: spring-petclinic-discovery-server
      tag: latest
    port: 8761
    replicaCount: 1

  customers-service:
    name: customers-service
    image:
      repository: spring-petclinic-customers-service
      tag: latest
    port: 8081
    replicaCount: 1

  visits-service:
    name: visits-service
    image:
      repository: spring-petclinic-visits-service
      tag: latest
    port: 8082
    replicaCount: 1

  vets-service:
    name: vets-service
    image:
      repository: spring-petclinic-vets-service
      tag: latest
    port: 8083
    replicaCount: 1

  